replay_buffer_size: 250000
replay_buffer_warmup_size: 10000
stacked_frames: 4
runner:
  starting_epsilon: 1.0
  epsilon_decay_rate: 0.9999
  epsilon_min: 0.05
  validate_every_episodes: 1000
  validation_episodes: 20
  num_workers: 2
trainer:
  eta: 0.0001
  gamma: 0.99
  batch_size: 32
  target_sync_every_steps: 5000
  save_checkpoint_every_steps: 10000
  update_actor_every_steps: 1000